"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, Mail, MessageCircle, RefreshCw, Send, ShieldCheck, UsersRound, X } from "lucide-react";

type Lead = { id: string; name: string; email: string; phone?: string; service?: string; message?: string; receivedAt?: string };
type Channel = "email" | "whatsapp";
type Draft = { lead: Lead; channel: Channel; subject: string; message: string };

function initialMessage(lead: Lead) { return `Hi ${lead.name.split(" ")[0]},\n\nThank you for reaching out to TrustNova about ${lead.service || "your project"}. I’d love to understand your goals and suggest the strongest next step.\n\nWould you be available for a short discovery call this week?\n\nWarmly,\nTrustNova`; }

export default function LeadDesk() {
  const [leads, setLeads] = useState<Lead[]>([]); const [source, setSource] = useState("loading"); const [selectedId, setSelectedId] = useState(""); const [channel, setChannel] = useState<Channel>("email"); const [subject, setSubject] = useState("A thoughtful next step for your project"); const [message, setMessage] = useState(""); const [reviewing, setReviewing] = useState<Draft | null>(null); const [notice, setNotice] = useState("");
  const selected = useMemo(() => leads.find((lead) => lead.id === selectedId) || leads[0], [leads, selectedId]);
  async function loadLeads() { setSource("loading"); try { const response = await fetch("/api/desk/leads", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(); setLeads(data.leads || []); setSource(data.source); } catch { setSource("unavailable"); setLeads([]); } }
  useEffect(() => { loadLeads(); }, []);
  useEffect(() => { if (selected) { setMessage(initialMessage(selected)); setSubject(`A thoughtful next step for ${selected.service || "your project"}`); } }, [selectedId, selected?.id]);
  async function sendApproved() { if (!reviewing) return; setNotice(""); try { const response = await fetch("/api/desk/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ channel: reviewing.channel, to: reviewing.channel === "email" ? reviewing.lead.email : reviewing.lead.phone, subject: reviewing.subject, message: reviewing.message }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Message could not be sent."); setNotice(`Sent to ${reviewing.lead.name}.`); setReviewing(null); } catch (caught) { setNotice(caught instanceof Error ? caught.message : "Message could not be sent."); setReviewing(null); } }
  async function signOut() { await fetch("/api/desk/session", { method: "DELETE" }); window.location.reload(); }
  return <main className="min-h-screen bg-brand-black px-4 py-5 text-brand-white sm:px-6 sm:py-8"><div className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-4 rounded-organic border border-brand-rule bg-brand-card px-5 py-5 shadow-soft sm:flex-row sm:items-center sm:px-7"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-accent-warm">TrustNova internal</p><h1 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">Lead desk</h1></div><div className="flex items-center gap-3"><button onClick={loadLeads} className="inline-flex items-center gap-2 rounded-full border border-brand-rule px-4 py-2 text-sm font-semibold text-brand-silver hover:text-brand-white"><RefreshCw size={15} />Refresh</button><button onClick={signOut} className="rounded-full border border-brand-rule px-4 py-2 text-sm font-semibold text-brand-silver hover:text-brand-white">Sign out</button></div></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-[340px_1fr]"><aside className="rounded-organic border border-brand-rule bg-brand-card p-4 shadow-soft"><div className="flex items-center justify-between px-2 py-3"><div className="flex items-center gap-2"><UsersRound size={19} className="text-accent-warm" /><h2 className="font-bold">New enquiries</h2></div><span className="rounded-full bg-brand-dark px-2.5 py-1 text-xs font-bold text-brand-silver">{leads.length}</span></div>{source === "preview" && <p className="mx-2 mb-3 rounded-lg bg-accent-warm/10 px-3 py-2 text-xs leading-relaxed text-accent-warm">Preview leads only. Connect your lead source to bring in website enquiries.</p>}{source === "unavailable" && <p className="mx-2 mb-3 rounded-lg bg-red-500/10 px-3 py-2 text-xs text-red-600">Your lead source could not be reached.</p>}<div className="max-h-[62vh] space-y-2 overflow-y-auto">{leads.map((lead) => <button key={lead.id} onClick={() => setSelectedId(lead.id)} className={`w-full rounded-xl p-4 text-left transition ${selected?.id === lead.id ? "bg-brand-dark" : "hover:bg-brand-dark/70"}`}><div className="flex items-start justify-between gap-2"><p className="font-semibold text-brand-white">{lead.name}</p><ChevronRight size={16} className="text-brand-dim" /></div><p className="mt-1 text-sm text-brand-silver">{lead.service || "New enquiry"}</p><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-brand-dim">{lead.message || lead.email}</p></button>)}{source !== "loading" && !leads.length && <p className="p-5 text-sm text-brand-silver">No enquiries yet.</p>}</div></aside>
      <section className="rounded-organic border border-brand-rule bg-brand-card p-6 shadow-soft sm:p-8">{selected ? <><div className="flex flex-col justify-between gap-4 border-b border-brand-rule pb-6 sm:flex-row"><div><p className="editorial-eyebrow text-accent-warm">Lead profile</p><h2 className="mt-2 text-2xl font-bold">{selected.name}</h2><p className="mt-2 text-sm text-brand-silver">{selected.email}{selected.phone ? ` · ${selected.phone}` : ""}</p></div><span className="self-start rounded-full bg-accent-sage/10 px-3 py-1.5 text-xs font-bold text-accent-sage">Ready for review</span></div><div className="mt-6 rounded-xl bg-brand-dark p-4"><p className="text-xs font-bold uppercase tracking-wider text-brand-dim">Their enquiry</p><p className="mt-2 text-sm leading-relaxed text-brand-silver">{selected.message || "No project details included."}</p></div><div className="mt-7 flex rounded-xl bg-brand-dark p-1" role="tablist">{(["email", "whatsapp"] as const).map((item) => <button type="button" key={item} onClick={() => setChannel(item)} className={`flex flex-1 items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-semibold transition ${channel === item ? "bg-brand-card text-brand-white shadow-soft" : "text-brand-silver"}`}>{item === "email" ? <Mail size={16} /> : <MessageCircle size={16} />}{item === "email" ? "Email" : "WhatsApp"}</button>)}</div><p className="mt-5 text-xs font-bold uppercase tracking-wider text-brand-dim">To: {channel === "email" ? selected.email : selected.phone || "No number supplied"}</p>{channel === "email" && <label className="mt-5 block text-sm font-semibold">Subject<input value={subject} onChange={(event) => setSubject(event.target.value)} className="mt-2 w-full rounded-xl border border-brand-rule bg-brand-black px-4 py-3 text-brand-white outline-none focus:border-accent-warm" /></label>}<label className="mt-5 block text-sm font-semibold">Draft message<textarea value={message} onChange={(event) => setMessage(event.target.value)} rows={9} className="mt-2 w-full resize-y rounded-xl border border-brand-rule bg-brand-black px-4 py-3 text-brand-white outline-none focus:border-accent-warm" /></label>{notice && <p className={`mt-4 rounded-xl p-3 text-sm ${notice.startsWith("Sent") ? "bg-accent-sage/10 text-accent-sage" : "bg-red-500/10 text-red-600"}`} role="status">{notice}</p>}<button disabled={!message.trim() || (channel === "whatsapp" && !selected.phone)} onClick={() => setReviewing({ lead: selected, channel, subject, message })} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand-white px-4 py-3 font-semibold text-brand-black disabled:opacity-50"><ShieldCheck size={18} />Review before sending</button></> : <div className="flex min-h-[400px] items-center justify-center text-brand-silver">Loading enquiries…</div>}</section></div></div>
  {reviewing && <div className="fixed inset-0 z-[2000] flex items-end bg-brand-white/45 p-4 backdrop-blur-sm sm:items-center sm:justify-center" role="dialog" aria-modal="true"><div className="w-full max-w-xl rounded-organic bg-brand-card p-6 shadow-card-hover sm:p-8"><div className="flex items-start justify-between"><div><p className="editorial-eyebrow text-accent-warm">Approval required</p><h2 className="mt-2 text-2xl font-bold">Send this outreach?</h2></div><button onClick={() => setReviewing(null)} className="rounded-full p-2 text-brand-silver hover:bg-brand-dark" aria-label="Close"><X size={20} /></button></div><div className="mt-6 rounded-xl border border-brand-rule bg-brand-black p-4 text-sm"><p className="text-brand-dim">{reviewing.channel === "email" ? "Email" : "WhatsApp"} to</p><p className="mt-1 font-semibold">{reviewing.channel === "email" ? reviewing.lead.email : reviewing.lead.phone}</p>{reviewing.channel === "email" && <><p className="mt-4 text-brand-dim">Subject</p><p className="mt-1 font-semibold">{reviewing.subject}</p></>}<p className="mt-4 whitespace-pre-wrap leading-relaxed text-brand-silver">{reviewing.message}</p></div><p className="mt-5 text-sm leading-relaxed text-brand-silver">This is the final checkpoint. Approving sends through the connected TrustNova account.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button onClick={() => setReviewing(null)} className="rounded-xl px-4 py-3 text-sm font-semibold text-brand-silver">Keep editing</button><button onClick={sendApproved} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-white px-5 py-3 text-sm font-semibold text-brand-black"><Send size={16} />Approve & send</button></div></div></div>}</main>;
}
